#!nobacktrace
(library (srfi :1)
  (export alist-cons
          alist-copy
          alist-delete
          alist-delete!
          any
          append
          append!
          append-map
          append-map!
          append-reverse
          append-reverse!
          assoc
          assoc/srfi-1
          assq
          assv
          break
          break!
          caaaar
          caaadr
          caaar
          caadar
          caaddr
          caadr
          caar
          cadaar
          cadadr
          cadar
          caddar
          cadddr
          caddr
          cadr
          car
          car+cdr
          cdaaar
          cdaadr
          cdaar
          cdadar
          cdaddr
          cdadr
          cdar
          cddaar
          cddadr
          cddar
          cdddar
          cddddr
          cdddr
          cddr
          cdr
          circular-list
          circular-list?
          concatenate
          concatenate!
          cons*
          count
          delete
          delete!
          delete-duplicates
          delete-duplicates!
          dotted-list?
          drop
          drop-right
          drop-right!
          drop-while
          eighth
          every
          fifth
          filter
          filter!
          filter-map
          find
          find-tail
          first
          fold
          fold-right
          fold-right/srfi-1
          for-each
          for-each/srfi-1
          fourth
          iota
          last
          last-pair
          length
          length+
          list
          list-copy
          list-index
          list-ref
          list-tabulate
          list=
          lset-adjoin
          lset-adjoin!
          lset-diff+intersection
          lset-diff+intersection!
          lset-difference
          lset-difference!
          lset-intersection
          lset-intersection!
          lset-union
          lset-union!
          lset-xor
          lset-xor!
          lset<=
          lset=
          make-list
          map
          map!
          map!/srfi-1
          map-in-order
          map/srfi-1
          member
          member/srfi-1
          memq
          memv
          ninth
          not-pair?
          null-list?
          null?
          pair-fold
          pair-fold-right
          pair-for-each
          pair?
          partition
          partition!
          proper-list?
          reduce
          reduce-right
          remove!/srfi-1
          remove/srfi-1
          reverse
          reverse!
          second
          seventh
          sixth
          span
          span!
          split-at
          split-at!
          take
          take!
          take-right
          take-while
          take-while!
          tenth
          third
          unfold
          unfold-right
          unzip1
          unzip2
          unzip3
          unzip4
          unzip5
          xcons
          zip)
  (import (srfi srfi-1)))
