#!nobacktrace
;;; Ypsilon Scheme System
;;; Copyright (c) 2004-2009 Y.FUJITA / LittleWing Company Limited.
;;; See license.txt for terms and conditions of use.

(library (ypsilon pango constants)

  (export PANGO_ATTR_ABSOLUTE_SIZE
          PANGO_ATTR_BACKGROUND
          PANGO_ATTR_FALLBACK
          PANGO_ATTR_FAMILY
          PANGO_ATTR_FONT_DESC
          PANGO_ATTR_FOREGROUND
          PANGO_ATTR_GRAVITY
          PANGO_ATTR_GRAVITY_HINT
          PANGO_ATTR_INVALID
          PANGO_ATTR_LANGUAGE
          PANGO_ATTR_LETTER_SPACING
          PANGO_ATTR_RISE
          PANGO_ATTR_SCALE
          PANGO_ATTR_SHAPE
          PANGO_ATTR_SIZE
          PANGO_ATTR_STRETCH
          PANGO_ATTR_STRIKETHROUGH
          PANGO_ATTR_STRIKETHROUGH_COLOR
          PANGO_ATTR_STYLE
          PANGO_ATTR_UNDERLINE
          PANGO_ATTR_UNDERLINE_COLOR
          PANGO_ATTR_VARIANT
          PANGO_ATTR_WEIGHT
          PANGO_RENDER_PART_BACKGROUND
          PANGO_RENDER_PART_FOREGROUND
          PANGO_RENDER_PART_STRIKETHROUGH
          PANGO_RENDER_PART_UNDERLINE
          PANGO_TAB_LEFT)

  (import (rnrs))

  (define PANGO_ATTR_INVALID 0)
  (define PANGO_ATTR_LANGUAGE 1)
  (define PANGO_ATTR_FAMILY 2)
  (define PANGO_ATTR_STYLE 3)
  (define PANGO_ATTR_WEIGHT 4)
  (define PANGO_ATTR_VARIANT 5)
  (define PANGO_ATTR_STRETCH 6)
  (define PANGO_ATTR_SIZE 7)
  (define PANGO_ATTR_FONT_DESC 8)
  (define PANGO_ATTR_FOREGROUND 9)
  (define PANGO_ATTR_BACKGROUND 10)
  (define PANGO_ATTR_UNDERLINE 11)
  (define PANGO_ATTR_STRIKETHROUGH 12)
  (define PANGO_ATTR_RISE 13)
  (define PANGO_ATTR_SHAPE 14)
  (define PANGO_ATTR_SCALE 15)
  (define PANGO_ATTR_FALLBACK 16)
  (define PANGO_ATTR_LETTER_SPACING 17)
  (define PANGO_ATTR_UNDERLINE_COLOR 18)
  (define PANGO_ATTR_STRIKETHROUGH_COLOR 19)
  (define PANGO_ATTR_ABSOLUTE_SIZE 20)
  (define PANGO_ATTR_GRAVITY 21)
  (define PANGO_ATTR_GRAVITY_HINT 22)
  (define PANGO_TAB_LEFT 0)
  (define PANGO_RENDER_PART_FOREGROUND 0)
  (define PANGO_RENDER_PART_BACKGROUND 1)
  (define PANGO_RENDER_PART_UNDERLINE 2)
  (define PANGO_RENDER_PART_STRIKETHROUGH 3)

  ) ;[end]
