PROG 	= ../ypsilon

STDLIB  = ../sitelib

all :
	@$(PROG) --sitelib=$(STDLIB) build-ucd-1.scm
	@$(PROG) --sitelib=$(STDLIB) build-ucd-2.scm
	@$(PROG) --sitelib=$(STDLIB) build-ucd-code.scm
	@$(PROG) --sitelib=$(STDLIB) build-lexeme-code.scm
