#!nobacktrace
(library (socket)
  (export AF_INET
          AF_INET6
          AF_UNSPEC
          AI_ADDRCONFIG
          AI_ALL
          AI_CANONNAME
          AI_NUMERICHOST
          AI_PASSIVE
          AI_V4MAPPED
          MSG_CONFIRM
          MSG_CTRUNC
          MSG_DONTROUTE
          MSG_DONTWAIT
          MSG_EOF
          MSG_EOR
          MSG_ERRQUEUE
          MSG_FIN
          MSG_MORE
          MSG_NOSIGNAL
          MSG_OOB
          MSG_PEEK
          MSG_PROBE
          MSG_RST
          MSG_SYN
          MSG_TRUNC
          MSG_WAITALL
          SHUT_RD
          SHUT_RDWR
          SHUT_WR
          SOCK_DGRAM
          SOCK_RAW
          SOCK_RDM
          SOCK_SEQPACKET
          SOCK_STREAM
          call-with-socket
          make-client-socket
          make-server-socket
          make-socket
          shutdown-output-port
          socket-accept
          socket-close
          socket-port
          socket-recv
          socket-send
          socket-shutdown
          socket?)
  (import (ypsilon socket)))
