#!nobacktrace
(library (ypsilon sdl)
  (export AUDIO_S16
          AUDIO_S16LSB
          AUDIO_S16MSB
          AUDIO_S16SYS
          AUDIO_S8
          AUDIO_U16
          AUDIO_U16LSB
          AUDIO_U16MSB
          AUDIO_U16SYS
          AUDIO_U8
          CD_ERROR
          CD_PAUSED
          CD_PLAYING
          CD_STOPPED
          CD_TRAYEMPTY
          IMG_InvertAlpha
          IMG_Linked_Version
          IMG_Load
          IMG_LoadBMP_RW
          IMG_LoadGIF_RW
          IMG_LoadJPG_RW
          IMG_LoadLBM_RW
          IMG_LoadPCX_RW
          IMG_LoadPNG_RW
          IMG_LoadPNM_RW
          IMG_LoadTGA_RW
          IMG_LoadTIF_RW
          IMG_LoadTyped_RW
          IMG_LoadXCF_RW
          IMG_LoadXPM_RW
          IMG_LoadXV_RW
          IMG_Load_RW
          IMG_ReadXPMFromArray
          IMG_isBMP
          IMG_isGIF
          IMG_isJPG
          IMG_isLBM
          IMG_isPCX
          IMG_isPNG
          IMG_isPNM
          IMG_isTIF
          IMG_isXCF
          IMG_isXPM
          IMG_isXV
          KMOD_ALT
          KMOD_CTRL
          KMOD_META
          KMOD_SHIFT
          MIX_FADING_IN
          MIX_FADING_OUT
          MIX_NO_FADING
          MUS_CMD
          MUS_MID
          MUS_MOD
          MUS_MP3
          MUS_MP3_MAD
          MUS_NONE
          MUS_OGG
          MUS_WAV
          Mix_AllocateChannels
          Mix_CloseAudio
          Mix_ExpireChannel
          Mix_FadeInChannelTimed
          Mix_FadeInMusic
          Mix_FadeInMusicPos
          Mix_FadeOutChannel
          Mix_FadeOutGroup
          Mix_FadeOutMusic
          Mix_FadingChannel
          Mix_FadingMusic
          Mix_FreeChunk
          Mix_FreeMusic
          Mix_GetChunk
          Mix_GetMusicHookData
          Mix_GetMusicType
          Mix_GetSynchroValue
          Mix_GroupAvailable
          Mix_GroupChannel
          Mix_GroupChannels
          Mix_GroupCount
          Mix_GroupNewer
          Mix_GroupOldest
          Mix_HaltChannel
          Mix_HaltGroup
          Mix_HaltMusic
          Mix_Linked_Version
          Mix_LoadMUS
          Mix_LoadMUS_RW
          Mix_LoadWAV_RW
          Mix_OpenAudio
          Mix_Pause
          Mix_PauseMusic
          Mix_Paused
          Mix_PausedMusic
          Mix_PlayChannelTimed
          Mix_PlayMusic
          Mix_Playing
          Mix_PlayingMusic
          Mix_QuerySpec
          Mix_QuickLoad_RAW
          Mix_QuickLoad_WAV
          Mix_RegisterEffect
          Mix_ReserveChannels
          Mix_Resume
          Mix_ResumeMusic
          Mix_RewindMusic
          Mix_SetDistance
          Mix_SetMusicCMD
          Mix_SetMusicPosition
          Mix_SetPanning
          Mix_SetPosition
          Mix_SetReverseStereo
          Mix_SetSynchroValue
          Mix_UnregisterAllEffects
          Mix_UnregisterEffect
          Mix_Volume
          Mix_VolumeChunk
          Mix_VolumeMusic
          SDLK_0
          SDLK_1
          SDLK_2
          SDLK_3
          SDLK_4
          SDLK_5
          SDLK_6
          SDLK_7
          SDLK_8
          SDLK_9
          SDLK_AMPERSAND
          SDLK_ASTERISK
          SDLK_AT
          SDLK_BACKQUOTE
          SDLK_BACKSLASH
          SDLK_BACKSPACE
          SDLK_BREAK
          SDLK_CAPSLOCK
          SDLK_CARET
          SDLK_CLEAR
          SDLK_COLON
          SDLK_COMMA
          SDLK_COMPOSE
          SDLK_DELETE
          SDLK_DOLLAR
          SDLK_DOWN
          SDLK_END
          SDLK_EQUALS
          SDLK_ESCAPE
          SDLK_EURO
          SDLK_EXCLAIM
          SDLK_F1
          SDLK_F10
          SDLK_F11
          SDLK_F12
          SDLK_F13
          SDLK_F14
          SDLK_F15
          SDLK_F2
          SDLK_F3
          SDLK_F4
          SDLK_F5
          SDLK_F6
          SDLK_F7
          SDLK_F8
          SDLK_F9
          SDLK_FIRST
          SDLK_GREATER
          SDLK_HASH
          SDLK_HELP
          SDLK_HOME
          SDLK_INSERT
          SDLK_KP0
          SDLK_KP1
          SDLK_KP2
          SDLK_KP3
          SDLK_KP4
          SDLK_KP5
          SDLK_KP6
          SDLK_KP7
          SDLK_KP8
          SDLK_KP9
          SDLK_KP_DIVIDE
          SDLK_KP_ENTER
          SDLK_KP_EQUALS
          SDLK_KP_MINUS
          SDLK_KP_MULTIPLY
          SDLK_KP_PERIOD
          SDLK_KP_PLUS
          SDLK_LALT
          SDLK_LAST
          SDLK_LCTRL
          SDLK_LEFT
          SDLK_LEFTBRACKET
          SDLK_LEFTPAREN
          SDLK_LESS
          SDLK_LMETA
          SDLK_LSHIFT
          SDLK_LSUPER
          SDLK_MENU
          SDLK_MINUS
          SDLK_MODE
          SDLK_NUMLOCK
          SDLK_PAGEDOWN
          SDLK_PAGEUP
          SDLK_PAUSE
          SDLK_PERIOD
          SDLK_PLUS
          SDLK_POWER
          SDLK_PRINT
          SDLK_QUESTION
          SDLK_QUOTE
          SDLK_QUOTEDBL
          SDLK_RALT
          SDLK_RCTRL
          SDLK_RETURN
          SDLK_RIGHT
          SDLK_RIGHTBRACKET
          SDLK_RIGHTPAREN
          SDLK_RMETA
          SDLK_RSHIFT
          SDLK_RSUPER
          SDLK_SCROLLOCK
          SDLK_SEMICOLON
          SDLK_SLASH
          SDLK_SPACE
          SDLK_SYSREQ
          SDLK_TAB
          SDLK_UNDERSCORE
          SDLK_UNDO
          SDLK_UNKNOWN
          SDLK_UP
          SDLK_WORLD_0
          SDLK_WORLD_1
          SDLK_WORLD_10
          SDLK_WORLD_11
          SDLK_WORLD_12
          SDLK_WORLD_13
          SDLK_WORLD_14
          SDLK_WORLD_15
          SDLK_WORLD_16
          SDLK_WORLD_17
          SDLK_WORLD_18
          SDLK_WORLD_19
          SDLK_WORLD_2
          SDLK_WORLD_20
          SDLK_WORLD_21
          SDLK_WORLD_22
          SDLK_WORLD_23
          SDLK_WORLD_24
          SDLK_WORLD_25
          SDLK_WORLD_26
          SDLK_WORLD_27
          SDLK_WORLD_28
          SDLK_WORLD_29
          SDLK_WORLD_3
          SDLK_WORLD_30
          SDLK_WORLD_31
          SDLK_WORLD_32
          SDLK_WORLD_33
          SDLK_WORLD_34
          SDLK_WORLD_35
          SDLK_WORLD_36
          SDLK_WORLD_37
          SDLK_WORLD_38
          SDLK_WORLD_39
          SDLK_WORLD_4
          SDLK_WORLD_40
          SDLK_WORLD_41
          SDLK_WORLD_42
          SDLK_WORLD_43
          SDLK_WORLD_44
          SDLK_WORLD_45
          SDLK_WORLD_46
          SDLK_WORLD_47
          SDLK_WORLD_48
          SDLK_WORLD_49
          SDLK_WORLD_5
          SDLK_WORLD_50
          SDLK_WORLD_51
          SDLK_WORLD_52
          SDLK_WORLD_53
          SDLK_WORLD_54
          SDLK_WORLD_55
          SDLK_WORLD_56
          SDLK_WORLD_57
          SDLK_WORLD_58
          SDLK_WORLD_59
          SDLK_WORLD_6
          SDLK_WORLD_60
          SDLK_WORLD_61
          SDLK_WORLD_62
          SDLK_WORLD_63
          SDLK_WORLD_64
          SDLK_WORLD_65
          SDLK_WORLD_66
          SDLK_WORLD_67
          SDLK_WORLD_68
          SDLK_WORLD_69
          SDLK_WORLD_7
          SDLK_WORLD_70
          SDLK_WORLD_71
          SDLK_WORLD_72
          SDLK_WORLD_73
          SDLK_WORLD_74
          SDLK_WORLD_75
          SDLK_WORLD_76
          SDLK_WORLD_77
          SDLK_WORLD_78
          SDLK_WORLD_79
          SDLK_WORLD_8
          SDLK_WORLD_80
          SDLK_WORLD_81
          SDLK_WORLD_82
          SDLK_WORLD_83
          SDLK_WORLD_84
          SDLK_WORLD_85
          SDLK_WORLD_86
          SDLK_WORLD_87
          SDLK_WORLD_88
          SDLK_WORLD_89
          SDLK_WORLD_9
          SDLK_WORLD_90
          SDLK_WORLD_91
          SDLK_WORLD_92
          SDLK_WORLD_93
          SDLK_WORLD_94
          SDLK_WORLD_95
          SDLK_a
          SDLK_b
          SDLK_c
          SDLK_d
          SDLK_e
          SDLK_f
          SDLK_g
          SDLK_h
          SDLK_i
          SDLK_j
          SDLK_k
          SDLK_l
          SDLK_m
          SDLK_n
          SDLK_o
          SDLK_p
          SDLK_q
          SDLK_r
          SDLK_s
          SDLK_t
          SDLK_u
          SDLK_v
          SDLK_w
          SDLK_x
          SDLK_y
          SDLK_z
          SDLKey
          SDLMod
          SDL_ACTIVEEVENT
          SDL_ACTIVEEVENTMASK
          SDL_ADDEVENT
          SDL_ANYFORMAT
          SDL_APPACTIVE
          SDL_APPINPUTFOCUS
          SDL_APPMOUSEFOCUS
          SDL_ASYNCBLIT
          SDL_AUDIO_PAUSED
          SDL_AUDIO_PLAYING
          SDL_AUDIO_STOPPED
          SDL_ActiveEvent
          SDL_AllocRW
          SDL_AudioDriverName
          SDL_AudioInit
          SDL_AudioQuit
          SDL_BUTTON_LEFT
          SDL_BUTTON_LMASK
          SDL_BUTTON_MIDDLE
          SDL_BUTTON_MMASK
          SDL_BUTTON_RIGHT
          SDL_BUTTON_RMASK
          SDL_BUTTON_WHEELDOWN
          SDL_BUTTON_WHEELUP
          SDL_BUTTON_X1
          SDL_BUTTON_X1MASK
          SDL_BUTTON_X2
          SDL_BUTTON_X2MASK
          SDL_BlitSurface
          SDL_BuildAudioCVT
          SDL_CDClose
          SDL_CDEject
          SDL_CDName
          SDL_CDNumDrives
          SDL_CDOpen
          SDL_CDPause
          SDL_CDPlay
          SDL_CDPlayTracks
          SDL_CDResume
          SDL_CDStatus
          SDL_CDStop
          SDL_ClearError
          SDL_CloseAudio
          SDL_CondBroadcast
          SDL_CondSignal
          SDL_CondWait
          SDL_CondWaitTimeout
          SDL_ConvertAudio
          SDL_ConvertSurface
          SDL_CreateCond
          SDL_CreateCursor
          SDL_CreateMutex
          SDL_CreateRGBSurface
          SDL_CreateRGBSurfaceFrom
          SDL_CreateSemaphore
          SDL_CreateThread
          SDL_CreateYUVOverlay
          SDL_DOUBLEBUF
          SDL_Delay
          SDL_DestroyCond
          SDL_DestroyMutex
          SDL_DestroySemaphore
          SDL_DisplayFormat
          SDL_DisplayFormatAlpha
          SDL_DisplayYUVOverlay
          SDL_EFREAD
          SDL_EFSEEK
          SDL_EFWRITE
          SDL_ENOMEM
          SDL_EVENT_RESERVED2
          SDL_EVENT_RESERVED3
          SDL_EVENT_RESERVED4
          SDL_EVENT_RESERVED5
          SDL_EVENT_RESERVED6
          SDL_EVENT_RESERVED7
          SDL_EVENT_RESERVEDA
          SDL_EVENT_RESERVEDB
          SDL_EnableKeyRepeat
          SDL_EnableUNICODE
          SDL_Error
          SDL_Event-type
          SDL_Event-type-set!
          SDL_EventState
          SDL_ExposeEvent
          SDL_FALSE
          SDL_FULLSCREEN
          SDL_FillRect
          SDL_Flip
          SDL_FreeCursor
          SDL_FreeRW
          SDL_FreeSurface
          SDL_FreeWAV
          SDL_FreeYUVOverlay
          SDL_GETEVENT
          SDL_GL_ACCELERATED_VISUAL
          SDL_GL_ACCUM_ALPHA_SIZE
          SDL_GL_ACCUM_BLUE_SIZE
          SDL_GL_ACCUM_GREEN_SIZE
          SDL_GL_ACCUM_RED_SIZE
          SDL_GL_ALPHA_SIZE
          SDL_GL_BLUE_SIZE
          SDL_GL_BUFFER_SIZE
          SDL_GL_DEPTH_SIZE
          SDL_GL_DOUBLEBUFFER
          SDL_GL_GREEN_SIZE
          SDL_GL_GetAttribute
          SDL_GL_GetProcAddress
          SDL_GL_LoadLibrary
          SDL_GL_Lock
          SDL_GL_MULTISAMPLEBUFFERS
          SDL_GL_MULTISAMPLESAMPLES
          SDL_GL_RED_SIZE
          SDL_GL_STENCIL_SIZE
          SDL_GL_STEREO
          SDL_GL_SWAP_CONTROL
          SDL_GL_SetAttribute
          SDL_GL_SwapBuffers
          SDL_GL_Unlock
          SDL_GL_UpdateRects
          SDL_GRAB_FULLSCREEN
          SDL_GRAB_OFF
          SDL_GRAB_ON
          SDL_GRAB_QUERY
          SDL_GetAppState
          SDL_GetAudioStatus
          SDL_GetClipRect
          SDL_GetCursor
          SDL_GetError
          SDL_GetEventFilter
          SDL_GetGammaRamp
          SDL_GetKeyName
          SDL_GetKeyRepeat
          SDL_GetKeyState
          SDL_GetModState
          SDL_GetMouseState
          SDL_GetRGB
          SDL_GetRGBA
          SDL_GetRelativeMouseState
          SDL_GetThreadID
          SDL_GetTicks
          SDL_GetVideoInfo
          SDL_GetVideoSurface
          SDL_HAT_CENTERED
          SDL_HAT_DOWN
          SDL_HAT_LEFT
          SDL_HAT_LEFTDOWN
          SDL_HAT_LEFTUP
          SDL_HAT_RIGHT
          SDL_HAT_RIGHTDOWN
          SDL_HAT_RIGHTUP
          SDL_HAT_UP
          SDL_HWACCEL
          SDL_HWPALETTE
          SDL_HWSURFACE
          SDL_Has3DNow
          SDL_Has3DNowExt
          SDL_HasAltiVec
          SDL_HasMMX
          SDL_HasMMXExt
          SDL_HasRDTSC
          SDL_HasSSE
          SDL_HasSSE2
          SDL_INIT_AUDIO
          SDL_INIT_CDROM
          SDL_INIT_EVENTTHREAD
          SDL_INIT_EVERYTHING
          SDL_INIT_JOYSTICK
          SDL_INIT_NOPARACHUTE
          SDL_INIT_TIMER
          SDL_INIT_VIDEO
          SDL_Init
          SDL_InitSubSystem
          SDL_JOYAXISMOTION
          SDL_JOYAXISMOTIONMASK
          SDL_JOYBALLMOTION
          SDL_JOYBALLMOTIONMASK
          SDL_JOYBUTTONDOWN
          SDL_JOYBUTTONDOWNMASK
          SDL_JOYBUTTONUP
          SDL_JOYBUTTONUPMASK
          SDL_JOYEVENTMASK
          SDL_JOYHATMOTION
          SDL_JOYHATMOTIONMASK
          SDL_JoyAxisEvent
          SDL_JoyBallEvent
          SDL_JoyButtonEvent
          SDL_JoyHatEvent
          SDL_JoystickClose
          SDL_JoystickEventState
          SDL_JoystickGetAxis
          SDL_JoystickGetBall
          SDL_JoystickGetButton
          SDL_JoystickGetHat
          SDL_JoystickIndex
          SDL_JoystickName
          SDL_JoystickNumAxes
          SDL_JoystickNumBalls
          SDL_JoystickNumButtons
          SDL_JoystickNumHats
          SDL_JoystickOpen
          SDL_JoystickOpened
          SDL_JoystickUpdate
          SDL_KEYDOWN
          SDL_KEYDOWNMASK
          SDL_KEYEVENTMASK
          SDL_KEYUP
          SDL_KEYUPMASK
          SDL_KeyboardEvent
          SDL_KillThread
          SDL_LASTERROR
          SDL_Linked_Version
          SDL_ListModes
          SDL_LoadBMP_RW
          SDL_LoadFunction
          SDL_LoadObject
          SDL_LoadWAV_RW
          SDL_LockAudio
          SDL_LockSurface
          SDL_LockYUVOverlay
          SDL_LowerBlit
          SDL_MOUSEBUTTONDOWN
          SDL_MOUSEBUTTONDOWNMASK
          SDL_MOUSEBUTTONUP
          SDL_MOUSEBUTTONUPMASK
          SDL_MOUSEEVENTMASK
          SDL_MOUSEMOTION
          SDL_MOUSEMOTIONMASK
          SDL_MapRGB
          SDL_MapRGBA
          SDL_MixAudio
          SDL_MouseButtonEvent
          SDL_MouseMotionEvent
          SDL_NOEVENT
          SDL_NOFRAME
          SDL_NUMEVENTS
          SDL_NumJoysticks
          SDL_OPENGL
          SDL_OPENGLBLIT
          SDL_OpenAudio
          SDL_PEEKEVENT
          SDL_PREALLOC
          SDL_PRESSED
          SDL_PauseAudio
          SDL_PeepEvents
          SDL_PixelFormat
          SDL_PollEvent
          SDL_PumpEvents
          SDL_PushEvent
          SDL_QUIT
          SDL_QUITMASK
          SDL_Quit
          SDL_QuitEvent
          SDL_QuitSubSystem
          SDL_RELEASED
          SDL_RESIZABLE
          SDL_RLEACCEL
          SDL_RLEACCELOK
          SDL_RWFromConstMem
          SDL_RWFromFP
          SDL_RWFromFile
          SDL_RWFromMem
          SDL_ReadBE16
          SDL_ReadBE32
          SDL_ReadBE64
          SDL_ReadLE16
          SDL_ReadLE32
          SDL_ReadLE64
          SDL_Rect
          SDL_RemoveTimer
          SDL_ResizeEvent
          SDL_SRCALPHA
          SDL_SRCCOLORKEY
          SDL_SWSURFACE
          SDL_SYSWMEVENT
          SDL_SYSWMEVENTMASK
          SDL_SaveBMP_RW
          SDL_SemPost
          SDL_SemTryWait
          SDL_SemValue
          SDL_SemWait
          SDL_SemWaitTimeout
          SDL_SetAlpha
          SDL_SetClipRect
          SDL_SetColorKey
          SDL_SetColors
          SDL_SetCursor
          SDL_SetEventFilter
          SDL_SetGamma
          SDL_SetGammaRamp
          SDL_SetModState
          SDL_SetPalette
          SDL_SetVideoMode
          SDL_ShowCursor
          SDL_SoftStretch
          SDL_Surface
          SDL_SysWMEvent
          SDL_TRUE
          SDL_ThreadID
          SDL_UNSUPPORTED
          SDL_USEREVENT
          SDL_UnloadObject
          SDL_UnlockAudio
          SDL_UnlockSurface
          SDL_UnlockYUVOverlay
          SDL_UpdateRect
          SDL_UpdateRects
          SDL_UpperBlit
          SDL_UserEvent
          SDL_VIDEOEXPOSE
          SDL_VIDEOEXPOSEMASK
          SDL_VIDEORESIZE
          SDL_VIDEORESIZEMASK
          SDL_VideoDriverName
          SDL_VideoInit
          SDL_VideoModeOK
          SDL_VideoQuit
          SDL_WM_GetCaption
          SDL_WM_GrabInput
          SDL_WM_IconifyWindow
          SDL_WM_SetCaption
          SDL_WM_SetIcon
          SDL_WM_ToggleFullScreen
          SDL_WaitEvent
          SDL_WaitThread
          SDL_WarpMouse
          SDL_WasInit
          SDL_WriteBE16
          SDL_WriteBE32
          SDL_WriteBE64
          SDL_WriteLE16
          SDL_WriteLE32
          SDL_WriteLE64
          SDL_iconv
          SDL_iconv_string
          SDL_keysym
          SDL_lltoa
          SDL_ltoa
          SDL_mutexP
          SDL_mutexV
          SDL_strlcat
          SDL_strlcpy
          SDL_strlwr
          SDL_strrev
          SDL_strupr
          SDL_ulltoa
          SDL_ultoa
          c-coerce-void*
          define-c-struct-methods
          make-SDL_Event
          make-bytevector-mapping)
  (import (ypsilon sdl constants)
          (ypsilon sdl types)
          (ypsilon sdl base)
          (ypsilon sdl image)
          (ypsilon sdl mixer)))
