#!nobacktrace
(library (ffi)
  (export alignof:double
          alignof:float
          alignof:int
          alignof:int16_t
          alignof:int32_t
          alignof:int64_t
          alignof:int8_t
          alignof:long
          alignof:short
          alignof:size_t
          alignof:void*
          bytevector-c-char-ref
          bytevector-c-char-set!
          bytevector-c-double-ref
          bytevector-c-double-set!
          bytevector-c-float-ref
          bytevector-c-float-set!
          bytevector-c-int-ref
          bytevector-c-int-set!
          bytevector-c-int16-ref
          bytevector-c-int16-set!
          bytevector-c-int32-ref
          bytevector-c-int32-set!
          bytevector-c-int64-ref
          bytevector-c-int64-set!
          bytevector-c-int8-ref
          bytevector-c-int8-set!
          bytevector-c-long-ref
          bytevector-c-long-set!
          bytevector-c-short-ref
          bytevector-c-short-set!
          bytevector-c-uint16-ref
          bytevector-c-uint32-ref
          bytevector-c-uint64-ref
          bytevector-c-uint8-ref
          bytevector-c-unsigned-int-ref
          bytevector-c-unsigned-long-ref
          bytevector-c-unsigned-short-ref
          bytevector-c-void*-ref
          bytevector-c-void*-set!
          c-coerce-void*
          c-function
          c-function/errno
          c-function/win32-lasterror
          c-sizeof
          define-c-struct-methods
          define-c-struct-type
          define-c-typedef
          load-shared-object
          lookup-shared-object
          make-bytevector-mapping
          make-cdecl-callback
          make-cdecl-callout
          make-stdcall-callback
          make-stdcall-callout
          on-darwin
          on-freebsd
          on-ia32
          on-linux
          on-openbsd
          on-posix
          on-windows
          on-x64
          shared-object-errno
          shared-object-win32-lasterror
          sizeof:int
          sizeof:long
          sizeof:short
          sizeof:size_t
          sizeof:void*
          win32-error->string)
  (import (ypsilon ffi)))
